services:
  - type: web
    name: fashion-bot
    env: python
    repo: https://github.com/Praddnyaaaa04/FashionBot
    branch: main
    pythonVersion: 3.10.8  # Specify the exact version here
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py  # Replace this with the actual entry point for your app
